language: r
sudo: false
cache: packages
r: 3.6.1
warnings_are_errors: false
r_check_args: "--no-build-vignettes --no-manual --as-cran --no-examples"
bioc_packages:
- GenomicRanges
- IRanges
- S4Vectors
- GenomeInfoDb
- VariantAnnotation
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
- chmod 755 ./travis-tool.sh
script: ./travis-tool.sh run_tests
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- travis_wait Rscript -e 'covr::codecov()'
