on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: test-only

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '4.0.2' ]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: ${{ matrix.R }}

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run tests
        run: |
          R CMD build .
          R CMD check *.tar.gz --no-manual
        shell: bash
