on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: test-only

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '4.0.2' ]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: ${{ matrix.R }}

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev

      - name: Install specific versions of dependencies
        run: |
          Rscript -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
          Rscript -e "remotes::install_version('igraph', version = '1.3.0', upgrade = 'never')"

      - name: Install dependencies from GitHub
        run: |
          Rscript -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
          Rscript -e "remotes::install_github('mskilab/gGnome', upgrade = 'never')"
          Rscript -e "remotes::install_github('mskilab/skidb', upgrade = 'never')"

      - name: Setup data for tests
        run: |
          mkdir -p ~/DB/GENCODE
          cp inst/extdata/test_data/gencode.v19.annotation.gtf.gr.rds ~/DB/GENCODE/gencode.v19.annotation.gtf.gr.rds

      - name: Run tests
        run: |
          R CMD build .
          R CMD check *.tar.gz --no-manual
        shell: bash
